# Generated by Django 5.0 on 2025-09-18 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplicativo.base')),
                ('nome', models.CharField(default='', help_text='Nome da pessoa', max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(help_text='Data de Nascimento', verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('Masculino', 'Male'), ('Feminino', 'Female'), ('Outros', 'Other'), ('NAO ESPECIFICADO', 'Nao Especificado')], default='NAO ESPECIFICADO', max_length=20, verbose_name='Gênero')),
            ],
            bases=('aplicativo.base',),
        ),
    ]
