# Generated by Django 5.0 on 2025-09-18 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2025, 9, 18), help_text='Data de Nascimento', verbose_name='Data de Nascimento'),
        ),
    ]
