# Generated by Django 5.0 on 2025-09-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0002_alter_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplicativo.base')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aplicativo.pessoa')),
            ],
            bases=('aplicativo.base',),
        ),
    ]
